sports/urls.py
from django.conf.urls import url

from .views import ParticipantCreate, ParticipantDelete, ParticipantDetail, ParticipantList, ParticipantUpdate
from .views import TeamCreate, TeamDelete, TeamDetail, TeamList, TeamUpdate
from .views import CoachCreate, CoachDelete, CoachDetail, CoachList, CoachUpdate
from .views import PerformanceCreate, PerformanceDelete, PerformanceUpdate

urlpatterns = [

    url('^participants/$', ParticipantList.as_view(), name='participants'),
    url(r'^participants/(?P<pk>\d+)/$', ParticipantDetail.as_view(), name='participant_detail'),
    url(r'participants/add/$', ParticipantCreate.as_view(), name='participant_add'),
    url(r'participants/(?P<pk>\d+)/update/$', ParticipantUpdate.as_view(), name='participant_update'),
    url(r'participants/(?P<pk>[0-9]+)/delete/$', ParticipantDelete.as_view(), name='participant_delete'),
    url(r'participants/(?P<pk>[0-9]+)/delete/confirm/$', ParticipantDelete.as_view(), name='participant_delete_confirm'),

    # New performance URL structure with a PK for participants and a PK for performances.
    url(r'participants/(?P<pk>[0-9]+)/performance/add/$', PerformanceCreate.as_view(), name='performance_add'),
    url(r'participants/(?P<pk>[0-9]+)/performance/(?P<performance_pk>\d+)/update/$', PerformanceUpdate.as_view(), name='performance_update'),
    url(r'participants/(?P<pk>[0-9]+)/performance/(?P<performance_pk>\d+)/delete/$', PerformanceDelete.as_view(), name='performance_delete'),

    url(r'teams/$', TeamList.as_view(), name='teams'),
    url(r'teams/add/$', TeamCreate.as_view(), name='team_add'),
    url(r'teams/(?P<pk>\d+)/$', TeamDetail.as_view(), name='team_detail'),
    url(r'teams/(?P<pk>\d+)/update/$', TeamUpdate.as_view(), name='team_update'),
    url(r'teams/(?P<pk>[0-9]+)/delete/$', TeamDelete.as_view(), name='team_delete'),
    url(r'teams/(?P<pk>[0-9]+)/delete/confirm/$', TeamDelete.as_view(), name='team_delete_confirm'),

    url(r'coaches/$', CoachList.as_view(), name='coaches'),
    url(r'coaches/add/$', CoachCreate.as_view(), name='coach_add'),
    url(r'coaches/(?P<pk>\d+)/$', CoachDetail.as_view(), name='coach_detail'),
    url(r'coaches/(?P<pk>\d+)/update/$', CoachUpdate.as_view(), name='coach_update'),
    url(r'coaches/(?P<pk>\d+)/delete/$', CoachDelete.as_view(), name='coach_delete'),
    url(r'coaches/(?P<pk>\d+)/delete/confirm/$', CoachDelete.as_view(), name='coach_delete_confirm'),

]

subscriptionform/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from home.views import index, MenuView


urlpatterns = [

    url(r'^$', index, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url('^', include('django.contrib.auth.urls')),
    url('^', include('sports.urls')),
    url('^', include('users.urls')),
    url(r'^menu/$', MenuView.as_view(), name='menu')

]

users/urls.py
from django.conf.urls import url

from .views import MyUserUpdate

urlpatterns = [

    url('^users/update/$', MyUserUpdate.as_view(), name='user_update'),

]

sports/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField

from club.models import Club, ClubMixin
from users.models import Person


class Participant(Person):
    """
    A model representing Participants of the sports event. It gathers some personal information
    by extending the Person class and assigns them to a sport and sport detail. Participants are
    automatically assigned to the Club to which the User that registered them belongs.
    """
    wheelchair_bound = models.BooleanField(_('wheelchair bound'), default=False)
    photo_choice = models.BooleanField(_('Photography allowed'), default=True)
    disciplines = models.ManyToManyField('Discipline', through='Performance')

    class Meta:
        verbose_name = _('Participant')

    def get_full_name(self):
        return self.first_name + " " + self.prefix + " " + self.last_name

    def _full_name(self):
        return '%s %s %s' % (self.first_name, self.prefix, self.last_name)
    full_name = property(_full_name)

    def __str__(self):
        return self.get_full_name()

    def get_absolute_url(self):
        return reverse('participant_detail', kwargs={'pk': self.pk})


class Coach(Person):
    phone_number = PhoneNumberField(_('phonenumber'), default='+31')
    email = models.EmailField(
        verbose_name=_('email address'),
        max_length=255,
        unique=True,
    )

    class Meta:
        verbose_name = _('Coach')
        verbose_name_plural = _('Coaches')

    def get_full_name(self):
        return self.first_name + " " + self.prefix + " " + self.last_name

    def _full_name(self):
        return '%s %s %s' % (self.first_name, self.prefix, self.last_name)
    full_name = property(_full_name)

    def __str__(self):
        return self.get_full_name()

    def get_absolute_url(self):
        return reverse('coach_detail', kwargs={'pk': self.pk})


class Sport(models.Model):
    """
    The sport model represents a sport that will be played during the event.
    """
    name = models.CharField(_('sport'), max_length=30)
    description = models.CharField(_('description'), max_length=150, blank=True)

    class Meta:
        verbose_name = _('Sport')

    def __str__(self):
        return self.name


class Discipline(models.Model):
    """
    A discipline is well, a discipline of a Sport that will be played during
    the event, for example the '50m sprint'.
    """
    name_of_discipline = models.CharField(_('discipline'), max_length=30)
    sport = models.ForeignKey(Sport)
    eventcode = models.CharField(max_length=12)

    class Meta:
        verbose_name = _('Discipline')

    def __str__(self):
        return self.name_of_discipline


class Performance(models.Model):
    """
    Intermediary model between a Participant and a Discipline, used to register a score, time,
    or other qualification.
    """
    discipline = models.ForeignKey(Discipline)
    participant = models.ForeignKey(Participant)
    qualification = models.CharField(_('qualification'), max_length=10, null=True)

    class Meta:
        # Makes sure a participant can only partake in a certain discipline once
        unique_together = ('discipline', 'participant',)

    def __str__(self):
        return str(self.qualification)

    def get_absolute_url(self):
        return reverse('participant_detail', kwargs={'pk':self.pk})


class Team(ClubMixin):
    """
    A team is a collection of Participants that is linked to a Club.
    """
    team_name = models.CharField(max_length=50)
    club = models.ForeignKey(Club)
    team_members = models.ManyToManyField(Participant, related_name='team_members')

    def __str__(self):
        return self.team_name

    def get_absolute_url(self):
        return reverse('team_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = _('Team')

sports/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Coach, Participant, Performance, Team, Discipline


class ParticipantForm(forms.ModelForm):

    class Meta:
        model = Participant
        fields = ('first_name', 'prefix', 'last_name', 'food_preferences', 'date_of_birth',
                  'wheelchair_bound', 'photo_choice',)


class TeamForm(forms.ModelForm):
    """
    Form for creating and editing Teams, with a custom filter to
    only display the participants belonging to the club of the logged in
    user.
    """
    def __init__(self, *args, **kwargs):
        super(TeamForm, self).__init__(*args, **kwargs)
        self.fields['team_members'].queryset = Participant.objects.all()

    class Meta:
        model = Team
        fields = ('team_name', 'team_members',)
        help_texts = {
            'team_members': _('Keep "control" or "command" on a Mac pressed to select multiple participants.')
        }


class CoachForm(forms.ModelForm):

    class Meta:
        model = Coach
        fields = ('first_name', 'prefix', 'last_name', 'date_of_birth', 'gender', 'phone_number', 'email', 'food_preferences', )


class PerformanceForm(forms.ModelForm):

    class Meta:
        model = Performance
        fields = ('participant', 'discipline', 'qualification',)


class DisciplineForm(forms.ModelForm):

    class Meta:
        model = Discipline
        fields = ('name_of_discipline',)

sports/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from .forms import CoachForm, ParticipantForm, PerformanceForm, TeamForm
from .models import Coach, Participant, Performance, Team


class ParticipantList(ListView):
    model = Participant


class ParticipantDetail(DetailView):
    model = Participant


class ParticipantCreate(CreateView):
    model = Participant
    form_class = ParticipantForm
    template_name = 'add_form.html'


class ParticipantUpdate(UpdateView):
    model = Participant
    form_class = ParticipantForm
    template_name = 'add_form.html'


class ParticipantDelete(DeleteView):
    model = Participant
    success_url = reverse_lazy('participants')
    template_name = 'confirm_delete.html'


class TeamList(ListView):
    model = Team


class TeamDetail(DetailView):
    model = Team


class TeamCreate(CreateView):
    model = Team
    form_class = TeamForm
    template_name = 'add_form.html'


class TeamUpdate(UpdateView):
    model = Team
    form_class = TeamForm
    template_name = 'add_form.html'


class TeamDelete(DeleteView):
    model = Team
    success_url = reverse_lazy('teams')
    template_name = 'confirm_delete.html'


class CoachList(ListView):
    model = Coach


class CoachDetail(DetailView):
    model = Coach


class CoachCreate(CreateView):
    model = Coach
    form_class = CoachForm
    template_name = 'add_form.html'


class CoachUpdate(UpdateView):
    model = Coach
    form_class = CoachForm
    template_name = 'add_form.html'


class CoachDelete(DeleteView):
    model = Coach
    success_url = reverse_lazy('coaches')
    template_name = 'confirm_delete.html'


class PerformanceCreate(CreateView):
    model = Performance
    form_class = PerformanceForm
    template_name = 'add_form.html'
    success_url = reverse_lazy('participants')
    pk_url_kwarg = 'performance_pk'

    def get_initial(self):
        return {'participant': self.kwargs['pk']}


class PerformanceUpdate(UpdateView):
    model = Performance
    form_class = PerformanceForm
    template_name = 'edit_performance_form.html'
    success_url = reverse_lazy('participants')
    pk_url_kwarg = 'performance_pk'


class PerformanceList(ListView):
    model = Performance


class PerformanceDelete(DeleteView):
    model = Performance
    success_url = reverse_lazy('participants')
    template_name = 'confirm_delete.html'
    pk_url_kwarg = 'performance_pk'

subscriptionform/templates/sports/coach_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="container">
        <h2>{% blocktrans %}Coach information{% endblocktrans %}</h2>
            <table class="base-table">
                <tbody>
                    <tr>
                        <td>{% blocktrans %}First name:{% endblocktrans %}</td>
                        <td>{{ coach.first_name }}</td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}Prefix:{% endblocktrans %}</td>
                        <td>{{ coach.prefix }}</td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}Last name:{% endblocktrans %}</td>
                        <td>{{ coach.last_name }}</td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}Date of birth:{% endblocktrans %}</td>
                        <td>{{ coach.date_of_birth }}</td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}Gender:{% endblocktrans %}</td>
                        <td>{{ coach.gender }}</td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}Phone number:{% endblocktrans %}</td>
                        <td>{{ coach.phone_number }}</td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}E-mail:{% endblocktrans %}</td>
                        <td>{{ coach.email }}</td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}Dietary restrictions:{% endblocktrans %}</td>
                        <td>{{ coach.food_preferences }}</td>
                    </tr>
                </tbody>
            </table>

    <a class="button-update" href="{% url 'coach_update' pk=coach.pk %}">{% blocktrans %}Edit coach{% endblocktrans %}</a>
    <a class="button-delete" href="{% url 'coach_delete' pk=coach.pk %}">{% blocktrans %}Delete this coach{% endblocktrans %}</a>
    <a class="button-add" href="{% url 'coach_add' %}">{% blocktrans %}Add another coach{% endblocktrans %}</a>
    <a class="button-return" href="{% url 'coaches' %}">{% blocktrans %}Return to coach list{% endblocktrans %}</a>
    </div>
{% endblock %}

subscriptionform/templates/sports/coach_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="container">
        <h2>{% blocktrans %}Coaches{% endblocktrans %}</h2>
        <table class="base-table">
            <thead>
                <tr>
                    <th>
                        {% blocktrans %}Coach Name{% endblocktrans %}
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for coach in coach_list %}
                    <tr>
                        <td>
                            <a href="{% url 'coach_detail' pk=coach.pk %}">{{ coach.full_name }}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <a class="button-add" href="{% url 'coach_add' %}">{% blocktrans %}Add Coach{% endblocktrans %}</a>
    </div>
{% endblock %}

subscriptionform/templates/sports/participant_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
    <p>{% blocktrans %}Are you sure you want to delete "{{ object }}"?{% endblocktrans %}</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

subscriptionform/templates/sports/participant_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="container">
        <h2>{% blocktrans %}Participant information {% endblocktrans %}</h2>
            <table class="base-table">
                <tbody>
                    <tr>
                        <td>{% blocktrans %}First name:{% endblocktrans %}</td>
                        <td>{{ participant.first_name }}</td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}Prefix:{% endblocktrans %}</td>
                        <td>{{ participant.prefix }}</td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}Last name:{% endblocktrans %}</td>
                        <td>{{ participant.last_name }}</td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}Date of birth:{% endblocktrans %}</td>
                        <td>{{ participant.date_of_birth }}</td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}Participates in:{% endblocktrans %}</td>
                        <td>{% for performance in participant.performance_set.all %}
                            <li><a href="{% url 'performance_update' pk=participant.pk performance_pk=performance.pk %}">{{ performance.discipline }}: {{ performance.qualification }}</a></li>
                            {% endfor %}
                            <a href ="{% url 'performance_add' pk=participant.pk %}"><span class="glyphicon glyphicon-plus"></span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}Wheelchair bound:{% endblocktrans %}</td>
                        <td>{{ participant.wheelchair_bound|yesno }}</td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}Photos allowed?{% endblocktrans %}</td>
                        <td>{{ participant.photo_choice|yesno }}</td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}Dietary restrictions:{% endblocktrans %}</td>
                        <td>{{ participant.food_preferences }}</td>
                    </tr>
                </tbody>
            </table>


    <a class="button-update" href="{% url 'participant_update' pk=participant.pk %}">{% blocktrans %}Edit participant{% endblocktrans %}</a>
    <a class="button-delete" href="{% url 'participant_delete' pk=participant.pk %}">{% blocktrans %}Delete this participant{% endblocktrans %}</a>
    <a class="button-add" href="{% url 'participant_add' %}">{% blocktrans %}Add another participant{% endblocktrans %}</a>
    <a class="button-return" href="{% url 'participants' %}">{% blocktrans %}Return to participant list{% endblocktrans %}</a>
    </div>
{% endblock %}

subscriptionform/templates/sports/participant_form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Welcome!' %}{% endblock %}
{% block content %}
    <form method="POST" class="add-form">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save</button>
    </form>

{% endblock %}

subscriptionform/templates/sports/participant_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="container">
        <h2>{% blocktrans %}Participants{% endblocktrans %}</h2>
        <table class="base-table">
            <thead>
                <tr>
                    <th>
                        {% blocktrans %}Participant Name{% endblocktrans %}
                    </th>
                    <th>
                        {% blocktrans %}Discipline{% endblocktrans %}
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for participant in participant_list %}
                    <tr>
                        <td>
                            <a href="{% url 'participant_detail' pk=participant.pk %}">{{ participant.full_name }}</a>
                        </td>
                        <td>{% for performance in participant.performance_set.all %}
                            <li>{{ performance.discipline }}</li>
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <a class="button-add" href="{% url 'participant_add' %}">{% blocktrans %}Add Participant{% endblocktrans %}</a>
    </div>
{% endblock %}

subscriptionform/templates/sports/performance_list.html
{#{% extends "base.html" %}#}
{#{% load i18n %}#}
{##}
{#{% block content %}#}
{#    <div class="container">#}
{#        <h2>{% blocktrans %}Performances for participant {{ participant.full_name }}{% endblocktrans %}</h2>#}
{#        <table class="base-table">#}
{#            <thead>#}
{#                <tr>#}
{#                    <th>#}
{#                        {% blocktrans %}Discipline{% endblocktrans %}#}
{#                    </th>#}
{#                    <th>#}
{#                        {% blocktrans %}Qualification{% endblocktrans %}#}
{#                    </th>#}
{#                </tr>#}
{#            </thead>#}
{#            <tbody>#}
{#                {% for discipline in participant.performance_set.all %}#}
{#                    <tr>#}
{#                        <td>#}
{#                            {{ discipline.discipline }}#}
{#                        </td>#}
{#                        <td>{% for performance in participant.performance.all %}#}
{#                            <li>{{ performance.discipline }}: {{ performance.qualification }}</li>#}
{#                            {% endfor %}#}
{#                        </td>#}
{#                    </tr>#}
{#                {% endfor %}#}
{#            </tbody>#}
{#        </table>#}
{##}
{#    </div>#}
{#{% endblock %}#}

subscriptionform/templates/sports/team_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="container">
        <h2>{% blocktrans %}Team information{% endblocktrans %}</h2>
            <table class="base-table">
                <tbody>
                    <tr>
                        <td>{% blocktrans %}Team name:{% endblocktrans %}</td>
                        <td>{{ team.team_name }}</td>
                    </tr>
                    <tr>
                        <td>{% blocktrans %}Team members:{% endblocktrans %}</td>
                        <td>{% for member in team.team_members.all %}
                            <li>
                                {{ member }}
                            </li>
                            {% endfor %}
                        </td>
                    </tr>
                </tbody>
            </table>

    <a class="button-update" href="{% url 'team_update' pk=team.pk %}">{% blocktrans %}Edit Team{% endblocktrans %}</a>
    <br>
    <a class="button-delete" href="{% url 'team_delete_confirm' pk=team.pk %}">{% blocktrans %}Delete Team{% endblocktrans %}</a>
    <br>
    <a class="button-return" href="{% url 'teams' %}">{% blocktrans %}Return to team list{% endblocktrans %}</a>
    </div>
{% endblock %}

subscriptionform/templates/sports/team_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="container">
        <h2>{% blocktrans %}Teams{% endblocktrans %}</h2>
        <table class="base-table">
            <thead>
                <tr>
                    <th>
                        {% blocktrans %}Team Name{% endblocktrans %}
                    </th>
                    <th>
                        {% blocktrans %}Team Size{% endblocktrans %}
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for team in team_list %}
                <tr>
                    <td>
                        <a href="{% url 'team_detail' pk=team.pk %}">{{ team.team_name }}</a></li>
                    </td>
                    <td>
                        {{ team.team_members|length }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    <a class="button-add" href="{% url 'team_add' %}">{% blocktrans %}Add Team{% endblocktrans %}</a>
{% endblock %}